Facebook connection removed due to stupidities of the library.
Yeah, it is perfectly normal to give this error on just a login on a
different machine:
com.facebook.FacebookOperationCanceledException: An unknown error
occurred